#!/bin/bash
source /ros_ws/devel/setup.bash
jupyter-notebook --allow-root  --ip='178.172.42.88' --port 8888  --NotebookApp.token='' --NotebookApp.password='' --notebook-dir=/catkin_ws/src/nn_pipeline/ 
