#!/bin/bash
source /ros_ws/devel/setup.bash
jupyter-notebook --allow-root  --ip='localhost' --port 8888  --NotebookApp.token='' --NotebookApp.password='' --notebook-dir=/root/catkin_ws/src/nn_pipeline/ 
