# use ubuntu 20.04 because we want to use ROS noetic
ARG TARGET="gpu"

FROM nvidia/cuda:11.6.2-cudnn8-devel-ubuntu20.04

#ARG CUDA_VERSION="11.3.1"
ARG nvidia_driver_major_version=525
ARG nvidia_binary_version="${nvidia_driver_major_version}.161.03"

#FROM nvidia_driver:11.3.1-base-ubuntu20.04
# FROM ros:noetic
LABEL maintainer "Boris Kuster <boris.kuster@ijs.si>"

SHELL ["/bin/bash","-c"]

################################################################
## BEGIN: ros:core
################################################################

# setup timezone
RUN echo 'Etc/UTC' > /etc/timezone && \
    ln -s /usr/share/zoneinfo/Etc/UTC /etc/localtime && \
    apt-get update && \
    apt-get install -q -y --no-install-recommends tzdata && \
    rm -rf /var/lib/apt/lists/*

# install packages
RUN apt update && apt install -q -y --no-install-recommends \
    dirmngr \
    gnupg2 \
    curl \
    nano \
    && rm -rf /var/lib/apt/lists/*

# setup keys
#RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654

# setup sources.list
#RUN echo "deb http://packages.ros.org/ros/ubuntu focal main" > /etc/apt/sources.list.d/ros1-latest.list

# setup environment
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

ENV ROS_DISTRO noetic

################################################################
## END: ros:core
## BEGIN: python3
################################################################

RUN apt update && apt install --no-install-recommends -y \
    software-properties-common \
    build-essential \
    wget 
 #nvidia-utils-${nvidia_driver_major_version}
    
RUN add-apt-repository universe

RUN apt update --fix-missing && apt install -y wget bzip2 ca-certificates zlib1g-dev libncurses5-dev libgdbm-dev \
    libglib2.0-0 libxext6 libsm6 libxrender1 libffi-dev \
    git \
    libusb-1.0-0-dev

RUN apt update && apt install -y python3-pip
RUN pip3 install --upgrade pip

RUN pip3 install empy matplotlib jupyter numpy-quaternion quaternionic shapely nano


################################################################
## END: python3
## BEGIN: Video/image module (openai-clip)
################################################################

# Image to text - OpenAI CLIP
RUN pip3 install open_clip_torch

# Language model - temporarily just chatgpt api
RUN pip3 install revChatGPT
# Text input to text output and code generation - GPT-like model (GPT-Neo)

################################################################
## END: Video/image module (openai-clip)
## BEGIN: Audio model (openai-whisper)
################################################################

RUN apt install -y portaudio19-dev ffmpeg
RUN pip3 install pyaudio webrtcvad halo ffmpeg-python

# OpenAI whisper
RUN pip3 install -U openai-whisper

# Text to speech TTS
RUN pip3 install TTS

# Install huggingface transformers from github
RUN pip3 install git+https://github.com/huggingface/transformers
RUN pip3 install accelerate bitsandbytes
################################################################
## END: Audio model (openai-whisper)
## BEGIN: ros:noetic
################################################################

# install ros packages
#RUN apt update && apt install --no-install-recommends -y \
#    ros-noetic-ros-core=1.5.0-1* \
#    ros-noetic-ros-base=1.5.0-1* \
#    rospy-message-converter \
#    python3-rosdep \
#    python3-rosinstall \
#    python3-vcstools \
#    python3-catkin-tools \
#    ros-noetic-tf \
#    ros-noetic-cv-bridge \
#    && rm -rf /var/lib/apt/lists/*
    


# bootstrap rosdep
#RUN rosdep init && \
#  rosdep update --rosdistro $ROS_DISTRO

################################################################
## END: ros:noetic
## BEGIN: python packages
################################################################

# RUN if [ "$TARGET" = "gpu" ] ; then \
#        pip3 install torch torchvision --extra-index-url https://download.pytorch.org/whl/cu113  \
#     else \
#        pip3 install torch torchvision \
#     fi

RUN pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116

#RUN pip3 install torch torchvision --extra-index-url https://download.pytorch.org/whl/cu113

# RUN pip3 install torch torchvision

RUN pip3 install rich matplotlib numpy pillow scikit-learn scipy tensorboard pyyaml opencv-python regex natsort shapely commentjson pycocotools cython scikit-image joblib==1.1.0 jsonpickle
RUN pip3 install lap cython_bbox

# Create local catkin workspace
ENV CATKIN_WS=/root/catkin_ws
ENV ROS_PYTHON_VERSION=3
RUN mkdir -p $CATKIN_WS/src/nn_pipeline
WORKDIR $CATKIN_WS

COPY nn_pipeline $CATKIN_WS/src/nn_pipeline

# Initialize local catkin workspace
#RUN source /opt/ros/${ROS_DISTRO}/setup.bash \
#    && cd $CATKIN_WS \
#    && rosdep install -y --from-paths . --ignore-src --rosdistro ${ROS_DISTRO}

# RUN update-alternatives --remove python /usr/bin/python \
#     && update-alternatives --install /usr/bin/python python /usr/local/bin/python3 10

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 10

# required for pyrealsense2
#RUN pip3 install rospkg
#RUN pip3 install rospy-message-converter

################################################################
## END: ROS
## BEGIN: realsense
################################################################

RUN apt install -y apt-transport-https
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE || sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE \
    && add-apt-repository "deb https://librealsense.intel.com/Debian/apt-repo $(lsb_release -cs) main" -u

################################################################
## END: realsense
## BEGIN: ROS (again?)
################################################################
RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
RUN apt update
RUN apt install -y ros-noetic-ros-base \
                   python3-rospy \
                   python3-catkin-tools \
                   python3-osrf-pycommon
RUN source /opt/ros/${ROS_DISTRO}/setup.bash

RUN apt install -y ros-${ROS_DISTRO}-cv-bridge ros-${ROS_DISTRO}-vision-opencv
#RUN source /opt/ros/${ROS_DISTRO}/setup.bash \
#    && cd $CATKIN_WS \
#    && catkin init \
#    # && catkin config -DPYTHON_EXECUTABLE=/usr/local/bin/python3.8 \
#    # && catkin config -DPYTHON_EXECUTABLE=/usr/local/bin/python3 -DPYTHON_INCLUDE_DIR=/usr/local/include/python3.8 -DPYTHON_LIBRARY=/usr/local/lib/libpython3.8.a \
#    && catkin config --install
#    # && cd src \
#    # && git clone -b noetic https://github.com/ros-perception/vision_opencv.git

# cv_bridge fix
#RUN sed -i 's/python3/python-py38/g' src/vision_opencv/cv_bridge/CMakeLists.txt



#RUN source /opt/ros/${ROS_DISTRO}/setup.bash \
#     && cd $CATKIN_WS \
#     && catkin build cv_bridge -DSETUPTOOLS_DEB_LAYOUT=OFF \ 
#     # I was getting some error without -DSETUPTOOLS_DEB_LAYOUT=OFF
#     && source install/setup.bash --extend


#    && catkin build
#    # && catkin install
#    # catkin install doesn't seem to do anything?

# ROS breaks opencv because python3 will try and default to the python2.7 version of opencv. Delete it.
# RUN rm /opt/ros/kinetic/lib/python2.7/dist-packages/cv2.so

################################################################
## END: ROS (again?)
################################################################

# Always source ros_catkin_entrypoint.sh when launching bash (e.g. when attaching to container)
RUN echo "source /entrypoint.sh" >> /root/.bashrc

COPY ./entrypoint.sh /
RUN chmod +x /entrypoint.sh

COPY ./run-jupyter /bin/run-jupyter
RUN chmod +x /bin/run-jupyter

ENTRYPOINT ["/entrypoint.sh"]

# # stop docker from exiting immediately
CMD tail -f /dev/null
